# Generated by Django 3.1.7 on 2021-03-01 13:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerApp', '0005_auto_20210301_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 1, 13, 23, 33, 124908, tzinfo=utc), verbose_name='date published'),
        ),
    ]
