# Generated by Django 3.1.7 on 2021-03-01 13:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerApp', '0006_auto_20210301_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 1, 13, 25, 14, 116360, tzinfo=utc), verbose_name='date published'),
        ),
    ]
